# Generated by Django 5.0.3 on 2024-03-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('descrip', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
