# Generated by Django 5.0.3 on 2024-03-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalogo/images/')),
                ('name', models.CharField(max_length=30)),
                ('descript', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('public_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='New',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
