# Generated by Django 5.0.3 on 2024-03-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_new_product_delete_new_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_product',
            old_name='descript',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='new_product',
            name='public_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
