# Generated by Django 5.0.3 on 2024-03-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="20240315"),
            preserve_default=False,
        ),
    ]
